version: '2.0'

services:
    client:
        build:
            context: ./react
            dockerfile: ./dockerfile
        volumes:
            - ./react:/client
            - /react/node_modulels
        ports:
            - 3000:3000
        environment:
            # Enabling hot reload
            - CHOKIDAR_USEPOLLING=true
            - PORT=3000
        depends_on:
            - server
    server:
        build:
            context: ./node
            dockerfile: ./dockerfile
        environment:
            - PORT=3001
            - MONGO_INITDB_ROOT_USERNAME=mern
            - MONGO_INITDB_ROOT_PASSWORD=merndocker
            - MONGO_URI=mongodb://db:27017
        volumes:
            - ./node:/server
            - /node/node_modulels
        ports:
            - 3001:3001
        depends_on:
            - db
    db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mern
            - MONGO_INITDB_ROOT_PASSWORD=merndocker
        volumes:
            - mongoDB:/data/db
        ports:
            - 27017:27017
volumes:
    mongoDB:
